language: python
python:
  - "3.7"
  - "3.8"

# enable docker in Travis
services:
  - docker
  
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+(-\S*)?$/

before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|^(LICENSE)|^(docs)'
      then
        echo "Only doc files were updated, not running the CI."
        exit
      fi

# command to install dependencies
install:
  - pip install tox tox-travis -U --force-reinstall

# command to run tests
script:
  - tox -vv
  - docker --version
  - make build
  - docker images
  - docker run `make version` --help
  - make docs

# push images to DockerHub and PyPI on tags
deploy:
  - provider: script
    script: bash docker_deploy.sh
    skip_cleanup: true
    on:
      tags: true
      python: "3.7"
      condition: -n "$DOCKER_PASSWORD"
  - provider: script
    script:  python -m pip install tox && tox -vve pypi_publish
    skip_cleanup: true
    on:
      tags: true
      python: "3.7"
      condition: -n "$TWINE_PASSWORD"
